// src/main/theme.js
export const themes = {
  // ---------------- [기존 테마] ----------------
  classic: {
    id: 'classic',
    name: '클래식 우드',
    bg: 'bg-slate-900',
    scoreboardBg: 'bg-slate-800 border-slate-700',
    boardBg: 'bg-amber-800 border-amber-950',
    holeBg: 'bg-amber-900 border-amber-950',
    holeInner: 'bg-amber-950',
  },
  neon: {
    id: 'neon',
    name: '사이버 네온',
    bg: 'bg-zinc-950',
    scoreboardBg: 'bg-zinc-900 border-cyan-500/50 shadow-cyan-500/20',
    boardBg: 'bg-zinc-900 border-cyan-500 shadow-cyan-500/30',
    holeBg: 'bg-black border-cyan-400/50',
    holeInner: 'bg-zinc-950',
  },
  candy: {
    id: 'candy',
    name: '스위트 캔디',
    bg: 'bg-pink-950',
    scoreboardBg: 'bg-pink-900/80 border-pink-700',
    boardBg: 'bg-pink-700 border-pink-900',
    holeBg: 'bg-pink-800 border-pink-950',
    holeInner: 'bg-pink-950',
  },
  matrix: {
    id: 'matrix',
    name: '매트릭스',
    bg: 'bg-black',
    scoreboardBg: 'bg-emerald-950/60 border-emerald-800 text-emerald-400',
    boardBg: 'bg-emerald-950 border-emerald-800',
    holeBg: 'bg-emerald-900 border-emerald-700',
    holeInner: 'bg-black',
  },
  sunset: {
    id: 'sunset',
    name: '선셋 오렌지',
    bg: 'bg-stone-950',
    scoreboardBg: 'bg-orange-950/70 border-orange-800',
    boardBg: 'bg-gradient-to-br from-orange-600 to-rose-700 border-orange-900',
    holeBg: 'bg-orange-900 border-orange-950',
    holeInner: 'bg-stone-950',
  },
  ocean: {
    id: 'ocean',
    name: '딥 오션',
    bg: 'bg-blue-950',
    scoreboardBg: 'bg-blue-900/50 border-blue-700',
    boardBg: 'bg-blue-800 border-blue-950',
    holeBg: 'bg-blue-900 border-blue-950',
    holeInner: 'bg-blue-950',
  },
  lavender: {
    id: 'lavender',
    name: '몽환 라벤더',
    bg: 'bg-purple-950',
    scoreboardBg: 'bg-purple-900/60 border-purple-700',
    boardBg: 'bg-purple-800 border-purple-950',
    holeBg: 'bg-purple-900 border-purple-950',
    holeInner: 'bg-purple-950',
  },
  midnight: {
    id: 'midnight',
    name: '미드나잇 골드',
    bg: 'bg-neutral-950',
    scoreboardBg: 'bg-neutral-900 border-amber-500/40',
    boardBg: 'bg-neutral-900 border-amber-600/60',
    holeBg: 'bg-neutral-950 border-amber-500/30',
    holeInner: 'bg-black',
  }
};